### ISSUE TITLE
多系统免登场景

### ISSUE THREAD

**Issue by shenjo** [Authing/spa-demo-react#1]
我这边有一个这样的场景：
a.com 是文档类系统，可以不登录查看
b.com 是管理系统，需要登录查看

用户现在b.com登录了之后，去a.com，这时a.com localStorage是空的，一般情况下就要跳转到统一认证页了。但是由于a.com是可以不登录就查看的，就必须得阻止跳转，因为不确认是否在其他系统登录了。这就导致实际是登录的，但是a.com无法得知这个状态。

请教下这种情况下应该如何处理

**Comment by yelexin** [comment]
https://docs.authing.cn/v2/reference/sdk-for-sso-spa.html#%E4%BB%A3%E7%A0%81%E5%8F%82%E8%80%83 参考下这个
